export default Strings = {
  appName: 'AGRO',
  RegisterNow: "Login or Register now",
  RegisterLeter: "Register leter",
  Register: 'Register',
  SendTheFollowingFormTo: "Send the following form to become an advertiser for Agrotratos Bolivia.",
  name: "name *",
  Surname: "Surname *",
  Userlogin: "User login *",
  Email: "Email *",
  ConfirmEmail: "Confirm Email*",
  SellerName: "Seller Name*",
  Important: "Important:",
  UsernameOrEmailAddress: "Username or email address*",
  Password: "Password*",
  ThisIsTheNameThatCustomers: " This is the name that customers will see in your ads. Please choose carefully.",
  IngreseNroDeTeléfono: "Ingrese Nro. de Teléfono de contacto, por favor describa sobre su rubro y lo que vende *",
  YouHaveAnAccountAlready: "You have an account already?   ",
  Login: "Log in",
  LetsLoginToContinue: "Let's log in to continue",
  newInAgrotratos: "new in Agrotratos?  ",
  DidYouForgetYourPassword: "Did you forget your password?",
  Home: "Home",
  Categories: "Categories",
  Add: "Add",
  News: 'News',
  More: "More",
  PRODUCERS: "PRODUCERS",
  SUPPLIERS: "SUPPLIERS",
  ConnectWithTheMost: "Connect with the most important agricultural producers in your area. Check the offers of grains, seeds, agricultural by-products and livestock.",
  KnowAllTheProductsAndServices: "Know all the products and services they have to offer you the Suppliers. You can find machinery and spare parts, properties (land) available for the activity, services and products.",
  Search: "Search",
  products: "products",
  Won: "Won",
  Grain : "Grain",
  Seeds : "Seeds"

};
